backend:
  name: git-gateway
  branch: master
media_folder: src/assets
public_folder: /assets
collections:
  - name: "pages"
    label: "Pages"
    label_singular: "Page"
    folder: "content/pages"
    slug: "{{fields.category}}--{{fields.slug}}"
    create: true
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Template"
        name: "template"
        default: "standard"
        widget: "select"
        options:
          - { label: "Standard Page", value: "standard" }
          - { label: "Guide Page", value: "guide" }
      - label: "Category"
        name: "category"
        widget: "relation"
        collection: "categories"
        valueField: "title"
        searchFields: ["title"]
      - label: "Slug"
        name: "slug"
        widget: "string"
        hint: "Don't include \"/\"s"
      - label: "Background Image"
        name: "bg_img"
        widget: "image"
      - label: "Sections"
        name: "sections"
        widget: "list"
        types:
          - label: "Content Block"
            name: "content_block"
            widget: "object"
            fields:
              - label: "TOC Title"
                name: "toc_title"
                widget: "string"
                hint: "Sections with TOC Title will show in the Table of Contents"
                required: false
              - label: "Markdown"
                name: "markdown"
                widget: "markdown"
                required: false
          - label: "Collapsable Content"
            name: "collapsable_content"
            widget: "object"
            fields:
              - label: "Type"
                name: "template"
                default: "accordion_1"
                widget: "select"
                options: 
                  - { label: "Accordion (full-width)", value: "accordion_1" }
                  - { label: "Accordion (2 column)", value: "accordion_2" }
                  - { label: "Tabs", value: "tabs" }
              - label: "Sections"
                name: "sections"
                widget: "list"
                fields:
                  - label: "Title"
                    name: "title"
                    widget: "string"
                  - label: "Body"
                    name: "markdown"
                    widget: "markdown"
          - label: "Callout Box"
            name: "callout_box"
            widget: "object"
            fields:
              - label: "Type"
                name: "template"
                default: "style_1"
                widget: "select"
                options: 
                  - { label: "Style 1 (Left-aligned)", value: "style_1" }
                  - { label: "Style 2 (Center-aligned)", value: "style_2" }
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Body"
                name: "markdown"
                widget: "markdown"
      - label: "Medical Reviewer"
        name: "reviewer"
        widget: "relation"
        collection: "reviewers"
        valueField: "title"
        searchFields: ["title"]
        required: false
  - name: "categories"
    label: "Categories"
    label_singular: "Category"
    folder: "content/categories"
    create: true
    fields:
      - label: "Category Title"
        name: "title"
        widget: "string"
      - label: "Category Image"
        name: "category_image"
        widget: "image"
  - name: "reviewers"
    label: "Reviewers (MD)"
    label_singular: "Reviewer"
    folder: "content/reviewers"
    create: true
    fields:
      - label: "Reviewer Name"
        name: "title"
        widget: "string"
      - label: "Photo"
        name: "photo"
        widget: "image"
      - label: "Bio"
        name: "bio"
        widget: "image"
