backend:
  name: git-gateway
  branch: master
media_folder: src/assets
public_folder: /assets
collections:
  - name: "pages"
    label: "Pages"
    label_singular: "Page" # Used in the UI, ie: "New Post"
    folder: "content/blog"
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "website-page",
        }
      - { label: "Title", name: "title", widget: "string" }
      - label: "Sections"
        name: "sections"
        widget: "list"
        required: false
        types:
          - label: "Body"
            name: "body"
            widget: "markdown"
            required: false
