backend:
  name: git-gateway
  branch: master
media_folder: src/assets
public_folder: /assets
collections:
  - name: "pages"
    label: "Pages"
    label_singular: "Page" # Used in the UI, ie: "New Post"
    folder: "content/pages"
    slug: "{{fields.category}}--{{fields.slug}}"
    create: true
    fields:
      - label: "Template Key"
        name: "templateKey"
        widget: "hidden"
        default: "seo-page-standard"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Category"
        name: "category"
        widget: "relation"
        collection: "categories"
        valueField: "category_title"
        searchFields: ["category_title"]
      - label: "Slug"
        name: "slug"
        widget: "string"
      - label: "Background Image"
        name: "bg_img"
        widget: "image"
      - label: "Sections"
        name: "sections"
        widget: "list"
        types:
          - label: "Content Block"
            name: "content_block"
            widget: "object"
            fields:
              - label: "Markdown"
                name: "markdown"
                widget: "markdown"
      - label: "Medical Reviewer"
        name: "reviewer"
        widget: "relation"
        collection: "reviewers"
        valueField: "category_title"
        searchFields: ["reviewer_name"]
  - name: "categories"
    label: "Categories"
    label_singular: "Category" # Used in the UI, ie: "New Post"
    folder: "content/categories"
    create: true
    fields:
      - label: "Category Title"
        name: "title"
        widget: "string"
      - label: "Category Image"
        name: "category_image"
        widget: "image"
  - name: "reviewers"
    label: "Reviewers (MD)"
    label_singular: "Reviewer" # Used in the UI, ie: "New Post"
    folder: "content/reviewers"
    create: true
    fields:
      - label: "Reviewer Name"
        name: "title"
        widget: "string"
      - label: "Photo"
        name: "reviewer_image"
        widget: "image"
      - label: "Bio"
        name: "reviewer_image"
        widget: "image"
