backend:
  name: git-gateway
  branch: master
media_folder: src/assets
public_folder: /assets
collections:
  - name: "categories"
    label: "Categories"
    label_singular: "Category" # Used in the UI, ie: "New Post"
    folder: "content/categories"
    create: true
    fields:
      - label: "Category Title"
        name: "category_title"
        widget: "string"
      - label: "Category Image"
        name: "category_image"
        widget: "image"
  - name: "pages"
    label: "Pages"
    label_singular: "Page" # Used in the UI, ie: "New Post"
    folder: "content/blog"
    slug: "{{fields.category}}--{{fields.slug}}"
    create: true
    fields:
      - label: "Template Key"
        name: "templateKey"
        widget: "hidden"
        default: "website-page"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Category"
        name: "category"
        widget: "select"
        options:
          - { label: "Aligners", value: "aligners" }
          - { label: "Braces", value: "braces" }
          - { label: "Oral Hygenie", value: "oral-hygenie" }
          - { label: "Teeth Straightening", value: "teeth-straightening" }
          - { label: "Whitening", value: "whitening" }
          - { label: "Conditions", value: "conditions" }
          - { label: "Dental Restoration", value: "dental-restoration" }
          - { label: "Oral Surgery", value: "oral-surgery" }
          - { label: "Orthodontics", value: "orthodontics" }
          - { label: "HyperByte", value: "hyperbyte" }
      - label: "Slug"
        name: "slug"
        widget: "string"
      - label: "Background Image"
        name: "bg_img"
        widget: "image"
      - label: "Sections"
        name: "sections"
        widget: "list"
        types:
          - label: "Content Block"
            name: "content_block"
            widget: "object"
            fields:
              - label: "Markdown"
                name: "markdown"
                widget: "markdown"