backend:
  name: git-gateway
  branch: master
media_folder: src/assets
public_folder: /assets
collections:
  - name: "pages"
    label: "Pages"
    label_singular: "Page" # Used in the UI, ie: "New Post"
    folder: "content/blog"
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "website-page",
        }
      - { label: "Title", name: "title", widget: "string" }
      - label: "Sections"
        name: "sections"
        widget: "list"
        required: false
        types:
          - label: "Body"
            name: "body"
            widget: "markdown"
          - label: "Row List With Image"
            name: "rowListWithImage"
            widget: "object"
            fields:
              - label: "List items"
                name: "items"
                widget: "list"
                fields:
                  - { label: "Image", name: "image", widget: "image" }
                  - { label: "Title", name: "title", widget: "text" }
                  - { label: "Body", name: "body", widget: "markdown" }
          - label: "Tick List With Text"
            name: "tickListWithText"
            widget: "object"
            fields:
              - label: "List Items"
                name: "items"
                widget: "list"
                fields:
                  - { label: "Icon", name: "icon", widget: "image" }
                  - { label: "Body", name: "body", widget: "text" }
                  - { label: "Body", name: "body", widget: "markdown" }
          - label: "Lifecycle"
            name: "lifecycle"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "text" }
              - { label: "Image", name: "image", widget: "image" }
              - label: "Top Left"
                name: "topLeft"
                widget: "object"
                fields:
                  - {
                      label: "Title",
                      name: "title",
                      widget: "text",
                      required: true,
                    }
                  - {
                      label: "Icon",
                      name: "icon",
                      widget: "image",
                      required: true,
                    }
                  - {
                      label: "Body",
                      name: "body",
                      widget: "text",
                      required: true,
                    }
                required: true
              - label: "Top Right"
                name: "topRight"
                widget: "object"
                fields:
                  - {
                      label: "Title",
                      name: "title",
                      widget: "text",
                      required: true,
                    }
                  - {
                      label: "Icon",
                      name: "icon",
                      widget: "image",
                      required: true,
                    }
                  - {
                      label: "Body",
                      name: "body",
                      widget: "text",
                      required: true,
                    }
                required: true
              - label: "Bottom Left"
                name: "bottomLeft"
                widget: "object"
                fields:
                  - {
                      label: "Title",
                      name: "title",
                      widget: "text",
                      required: true,
                    }
                  - {
                      label: "Icon",
                      name: "icon",
                      widget: "image",
                      required: true,
                    }
                  - {
                      label: "Body",
                      name: "body",
                      widget: "text",
                      required: true,
                    }
                required: true
              - label: "Bottom Right"
                name: "bottomRight"
                widget: "object"
                fields:
                  - {
                      label: "Title",
                      name: "title",
                      widget: "text",
                      required: true,
                    }
                  - {
                      label: "Icon",
                      name: "icon",
                      widget: "image",
                      required: true,
                    }
                  - {
                      label: "Body",
                      name: "body",
                      widget: "text",
                      required: true,
                    }
                required: true
          - label: "Testimonial"
            name: "testimonial"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "text" }
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Body", name: "body", widget: "markdown" }
          - label: "Request Demo"
            name: "requestDemo"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "text" }
