backend:
  name: git-gateway
  branch: master
media_folder: src/assets
public_folder: /assets
collections:
  - name: "pages"
    label: "Pages"
    label_singular: "Page" # Used in the UI, ie: "New Post"
    folder: "content/blog"
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "website-page",
        }
      - {
          label: "Title",
          name: "title",
          widget: "string",
        }
      - {
          label: "Slug",
          name: "slug",
          widget: "string",
        }
      - label: "Category"
        name: "category"
        widget: "select"
        options:
          - { label: "Aligners", value: "aligners" }
          - { label: "Braces", value: "braces" }
          - { label: "Oral Hygenie", value: "oral-hygenie" }
          - { label: "Teeth Straightening", value: "teeth-straightening" }
          - { label: "Whitening", value: "whitening" }
          - { label: "Conditions", value: "conditions" }
          - { label: "Dental Restoration", value: "dental-restoration" }
          - { label: "Oral Surgery", value: "oral-surgery" }
          - { label: "Orthodontics", value: "orthodontics" }
          - { label: "HyperByte", value: "hyperbyte" }
      - label: "Background Image"
        name: "bg_img"
        widget: "image"
      - label: "Sections"
        name: "sections"
        widget: "list"
        fields:
          - label: "Markdown"
            name: "markdown"
            widget: "markdown"
          - label: "Image"
            name: "image"
            widget: "image"
      - { label: "Body", name: "body", widget: "markdown", required: false }